[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"Session_E8" 
"DefaultSession" 
[CONFIGURATIONS]
"Debug" 
[CURRENT_CONFIGURATION]
"Debug" 
[CURRENT_SESSION]
"Session_E8" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"Session_E8" 
"DefaultSession" 
[GENERAL_DATA_SESSION_Session_E8]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_Session_E8]
[END]
