[HIMDBVersion]
2.0
[DATABASE_VERSION]
"1.1" 
[SESSIONS_]
"Debug_M16C_E8_SYSTEM" 
"DefaultSession" 
[CONFIGURATIONS]
"Debug" 
"Release" 
[CURRENT_CONFIGURATION]
"Debug" 
[CURRENT_SESSION]
"Debug_M16C_E8_SYSTEM" 
[GENERAL_DATA_PROJECT]
"FDT_UserBootAreaFiles" "" 
[GENERAL_DATA_CONFIGURATION_Debug]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Debug]
"DefaultSession" 
"Debug_M16C_E8_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_Release]
"PROJECT_FILES_MODIFIED_DATA_TAG" "FALSE" 
[SESSIONS_Release]
"DefaultSession" 
"Debug_M16C_E8_SYSTEM" 
[GENERAL_DATA_CONFIGURATION_SESSION_Release_Debug_M16C_E8_SYSTEM]
[GENERAL_DATA_SESSION_Debug_M16C_E8_SYSTEM]
[GENERAL_DATA_SESSION_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_DefaultSession]
[GENERAL_DATA_CONFIGURATION_SESSION_Debug_Debug_M16C_E8_SYSTEM]
[GENERAL_DATA_CONFIGURATION_SESSION_Release_DefaultSession]
[END]
